import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideCol from './components/SideCol'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className='flex flex-col'>
      {/* <SideCol/> */}
      </div>
    {children}</body>
    </html>
  )
}